### ISSUE TITLE
User testing checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-arquillian-managed#26]
- [ ] Record the time it takes to go through the entire guide
- [ ] Test each step in the guide is clear to understand
- [ ] Ensure no logic errors
- [ ] Resolve anything that does not work
- [ ] Resolve anything usability issues (confusing or hard to follow)
- [ ] Achieve basic understanding/working knowledge of the topic in the guide
