### ISSUE TITLE
Readiness checklist

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-arquillian-managed#46]
Readiness checklist

* [x]  Development - Charles, Eveline
* [x]  Content Review - Eveline
* [x]  Peer Review - Gilbert, Andrew
* [x]  SME Review - Charles
* [x]  User Review - Tommy, Rachel
* [x] Multipane Review - Justine
* [x]  Signoff Review - YK
